import avatar from '../../../assets/images/admin/avar.png'
const users = [
  {
    id: 1,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1200,
    frequency: 7,
    totalInteractions: 2000
  },
  {
    id: 2,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1200,
    frequency: 7,
    totalInteractions: 2000
  },
  {
    id: 3,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1200,
    frequency: 7,
    totalInteractions: 2000
  },
  {
    id: 4,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1200,
    frequency: 7,
    totalInteractions: 2000
  },
  {
    id: 5,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1100,
    frequency: 6,
    totalInteractions: 1800
  },
  {
    id: 6,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1200,
    frequency: 7,
    totalInteractions: 2000
  },
  {
    id: 7,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1200,
    frequency: 7,
    totalInteractions: 2000
  },
  {
    id: 8,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1200,
    frequency: 7,
    totalInteractions: 2000
  },
  {
    id: 9,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1200,
    frequency: 7,
    totalInteractions: 2000
  },
  {
    id: 10,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 950,
    frequency: 5,
    totalInteractions: 1500
  },
  {
    id: 11,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1200,
    frequency: 7,
    totalInteractions: 2000
  },
  {
    id: 12,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 980,
    frequency: 6,
    totalInteractions: 1600
  },
  {
    id: 13,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1000,
    frequency: 6,
    totalInteractions: 1700
  },
  {
    id: 14,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 890,
    frequency: 5,
    totalInteractions: 1400
  },
  {
    id: 15,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1200,
    frequency: 7,
    totalInteractions: 2000
  },
  {
    id: 16,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 920,
    frequency: 5,
    totalInteractions: 1450
  },
  {
    id: 17,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1020,
    frequency: 6,
    totalInteractions: 1650
  },
  {
    id: 18,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1100,
    frequency: 6,
    totalInteractions: 1700
  },
  {
    id: 19,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1200,
    frequency: 7,
    totalInteractions: 2000
  },
  {
    id: 20,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 950,
    frequency: 5,
    totalInteractions: 1500
  },
  // Các user từ 21–35 tương tự:
  ...Array.from({ length: 15 }, (_, i) => ({
    id: 21 + i,
    name: 'Nguyễn Thanh Phong',
    email: 'phong@gmail.com',
    phone: '0123456789',
    gender: 'Nam',
    emotion: 1,
    status: 'Đang hoạt động',
    date: '03/08/2025',
    avatar: { avatar },
    totalConsults: 1000 + (i % 5) * 50,
    frequency: 5 + (i % 3),
    totalInteractions: 1500 + (i % 5) * 100
  }))
];

export default users;
